import './globals.css';
// import './components/basic/navbar.module.css'
import { Inter } from 'next/font/google'
import Header from "./components/basic/header";
import Banner from './components/basic/Banner';
import Searchbar from './components/basic/Searchbar';

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Index',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="pt-br">
            <head />
            
            <body className={`
                bg-gray-200
            `}>
                <Header />
                <Banner />
                <main className={`
                    w-full max-w-3xl mx-auto
                `}>
                    {children}
                </main>
            </body>
        </html>
    )
}
