import './globals.css';
// import './components/basic/navbar.module.css'
import { Inter } from 'next/font/google'
import Header from "./components/basic/header";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Index',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="pt-br">
            <head />
            <body className={inter.className}>
                <Header />
                {children}
            </body>
        </html>
    )
}
